### ISSUE TITLE
i hit update cache and get an error

### ISSUE THREAD

**Issue by sigxo** [Strappazzon/drg-mint-notag#1]
![image](https://github.com/Strappazzon/drg-mint-notag/assets/173160805/fe530252-caa8-490a-bc62-9b0a593fae58)

**Comment by Strappazzon** [comment]
This is a problem with mint itself and not with my fork.
See: https://github.com/trumank/mint/issues/126

To fix the issue:
- Find what mod has been deleted from mod.io
  - Unfortunately that means opening each mod's mod.io page in your web browser
- Delete the mod from mint
- Delete the cache folder `%LOCALAPPDATA%\drg-mod-integration\cache`
- Update the cache again
